name: Auto Merge Game Data
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Stitch Split Files Together
        run: |
          cd build
          cat 2facc552a7176a3c4f6184e293ead869.data.unityweb.part1 2facc552a7176a3c4f6184e293ead869.data.unityweb.part2 2facc552a7176a3c4f6184e293ead869.data.unityweb.part3 > 2facc552a7176a3c4f6184e293ead869.data.unityweb
          rm *.part*

      - name: Commit and Push Large Asset
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@://github.com'
          git add build/2facc552a7176a3c4f6184e293ead869.data.unityweb
          git commit -m "Automated data file merge bypass" || exit 0
          git push
